# Generated by Django 4.1.7 on 2023-09-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_profile_image_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='D:/FSD_group/new_backend2/mysite/media/profile/download_1.jpeg', upload_to='profile/'),
        ),
    ]
