# Generated by Django 4.1.7 on 2023-09-28 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cast',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Jain', 'Jain'), ('Punjabi', 'Punjabi'), ('Sindhi', 'Sindhi')], default='Hindu', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 28, 12, 43, 34, 373541)),
        ),
        migrations.AddField(
            model_name='profile',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.CharField(choices=[("4'6", "4'6"), ("4'7", "4'7"), ("4'8", "4'8"), ("4'9", "4'9"), ("5'0", "5'0"), ("5'1", "5'1"), ("5'2", "5'2"), ("5'3", "5'3"), ("5'4", "5'4"), ("5'5", "5'5"), ("5'6", "5'6"), ("5'7", "5'7"), ("5'8", "5'8"), ("5'9", "5'9"), ("6'0", "6'0"), ("6'1", "6'1"), ("6'2", "6'2"), ("6'3", "6'3"), ("6'4", "6'4"), ("6'5", "6'5"), ("6'6", "6'6"), ("6'7", "6'7"), ("6'8", "6'8"), ("6'9", "6'9"), ("7'0", "7'0")], default="5'9", max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='income',
            field=models.CharField(choices=[('0-2.5', '0-2.5'), ('2.5-5.0', '2.5-5.0'), ('5.0-7.5', '5.0-7.5'), ('7.5-10', '7.5-10'), ('10-20', '10-20'), ('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50+', '50+')], default='0-2.5', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.PositiveBigIntegerField(default=1234567890, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='prlocation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('single', 'single'), ('divorced', 'divorced'), ('widowed', 'widowed')], default='single', max_length=100),
        ),
    ]
