# Generated by Django 4.1.7 on 2023-09-29 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile_cast_profile_date_profile_disability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 29, 8, 56, 6, 56234)),
        ),
    ]
