# Generated by Django 4.1.7 on 2023-09-29 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_profile_date_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 29, 11, 42, 56, 292911)),
        ),
    ]
