# Generated by Django 4.1.7 on 2023-09-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_profile_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='email',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('email', 'profile')},
        ),
    ]
