# Generated by Django 4.1.7 on 2023-10-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_customuser_is_active_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
