# Generated by Django 4.1.7 on 2023-10-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_profile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
